# Change this!
LEVEL := 01

###############################################
###############################################
###############################################

GPU := B200
SRC := level_$(LEVEL).cu
OUT := level_$(LEVEL).out
CMD := ./level_$(LEVEL).out
CONFIG := standalone
NVCCFLAGS += -lcublas
include ../../common.mk
